# Generated by Django 3.1.14 on 2025-05-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Question Name (for internal use)')),
                ('text', models.TextField(verbose_name='Question Text (HTML)')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order in Test')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.question', verbose_name='Question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sex Description')),
            ],
            options={
                'verbose_name_plural': 'Sex Options',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Test Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test Description')),
                ('min_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Minimum Passing Score')),
                ('questions', models.ManyToManyField(through='quiz_plugin.QuestionInTest', to='quiz_plugin.Question', verbose_name='Quizzes in Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Execution Code')),
                ('execution_time', models.DateTimeField(auto_now_add=True, verbose_name='Execution Timestamp')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='User Age')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Total Score')),
                ('IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP Address')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration (minutes)')),
                ('revision_date', models.DateTimeField(blank=True, null=True, verbose_name='Revision Date by Medical Professional')),
                ('note', models.TextField(blank=True, null=True, verbose_name="Medical Professional's Note")),
                ('id_sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_plugin.sex', verbose_name='User Sex')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.test', verbose_name='Test Performed')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='quiz_plugin_quizpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.test', verbose_name='Select Test')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='questionintest',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.test', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Answer Text (HTML)')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Score (-1.00 to 1.00)')),
                ('correction', models.TextField(blank=True, null=True, verbose_name='Explanation for incorrect answer (HTML)')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_plugin.question', verbose_name='Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='questionintest',
            unique_together={('id_question', 'id_test')},
        ),
        migrations.CreateModel(
            name='GivenAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.answer', verbose_name='Answer Given')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.question', verbose_name='Question for this Answer')),
                ('id_testExecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.testexecution', verbose_name='Test Execution')),
            ],
            options={
                'unique_together': {('id_testExecution', 'id_question')},
            },
        ),
    ]
