# Generated by Django 3.1.14 on 2025-05-22 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givenanswer',
            name='id_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_in_executions', to='quiz_plugin.answer'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers_for_question', to='quiz_plugin.question'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='id_testExecution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='quiz_plugin.testexecution'),
        ),
    ]
