# Generated by Django 3.1.14 on 2025-05-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_plugin', '0002_auto_20250523_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpluginmodel',
            name='test',
        ),
    ]
