# Generated by Django 3.1.14 on 2025-05-23 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_plugin', '0003_remove_quizpluginmodel_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by Medical Professional'),
        ),
    ]
