# Generated by Django 3.1.14 on 2025-06-20 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_plugin', '0004_testexecution_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score (-1.00 to 1.00)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='min_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Minimum Passing Score'),
        ),
    ]
