# Generated by Django 3.1.14 on 2025-06-20 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_plugin', '0005_auto_20250620_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givenanswer',
            name='id_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.answer'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.question'),
        ),
        migrations.AlterField(
            model_name='questionintest',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.question'),
        ),
        migrations.AlterField(
            model_name='questionintest',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.test'),
        ),
        migrations.AlterField(
            model_name='questionintest',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='IP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='execution_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='id_sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_plugin.sex'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_plugin.test'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='revision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
