# Generated by Django 3.1.14 on 2025-06-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_plugin', '0006_auto_20250620_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.AlterField(
            model_name='test',
            name='min_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Minimum Passing Score'),
        ),
        migrations.DeleteModel(
            name='QuestionInTest',
        ),
    ]
