# Generated by Django 3.1.14 on 2025-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_plugin', '0007_auto_20250624_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='quiz_plugin.Question', verbose_name='Quizzes in Test'),
        ),
    ]
